gemini:
  model: "gemini-1.5-flash-latest"
  endpoint: "https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent"
  prompt_template: |
    Проанализируй изображение счетчика и верни только число показаний. 
    Не добавляй ничего, кроме результата.