openapi: 3.0.0
info:
  title: Сервис распознавания счетчиков
  description: API для распознавания показаний счетчиков на фотографиях
  version: 1.0.0
paths:
  /recognize:
    post:
      summary: Распознать показания счетчика
      description: Отправка фотографии счетчика и номера телефона для распознавания данных.
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                phone_number:
                  type: string
                  description: Номер телефона клиента.
                  example: "+79001234567"
                  pattern: "^\\+[1-9]\\d{1,14}$" # Стандарт E.164
                image:
                  type: string
                  format: binary
                  description: Фотография счетчика (электрического или газового).
      responses:
        '200':
          description: Успешное распознавание.
          content:
            application/json:
              schema:
                type: object
                properties:
                  phone_number:
                    type: string
                    example: "+79001234567"
                  meter_reading:
                    type: string
                    description: Показания счетчика.
                    example: "12345.67"
                  timestamp:
                    type: string
                    format: date-time
                    description: Дата и время распознавания.
        '400':
          description: Ошибка валидации запроса или неверный формат данных.
        '401':
          description: Неверный или отсутствующий API Key.
        '500':
          description: Внутренняя ошибка сервера.
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key